### ISSUE TITLE
PHP Warning:  Use of undefined constant WP_REPOSIDGET_HOMEPAGE

### ISSUE THREAD

**Issue by LufoX11** [myst729/wp-reposidget#5]
Hi! First of all, thank you for your plugin. I use it and I find it very useful.
I'm getting this PHP warning in logs:

```
PHP Warning:  Use of undefined constant WP_REPOSIDGET_HOMEPAGE - assumed 'WP_REPOSIDGET_HOMEPAGE' (this will throw an Error in a future version of PHP) in /var/www/.../wp-content/plugins/wp-reposidget/wp-reposidget.php on line 14
PHP Warning:  Use of undefined constant WP_REPOSIDGET_USERAGENT - assumed 'WP_REPOSIDGET_USERAGENT' (this will throw an Error in a future version of PHP) in /var/www/.../wp-content/plugins/wp-reposidget/wp-reposidget.php on line 15
```

It is as easy as replacing both constants in wp-reposidget.php to 'WP_REPOSIDGET_HOMEPAGE' and 'WP_REPOSIDGET_USERAGENT'.

Would it be possible for you to do it? Thank you!

**Comment by myst729** [comment]
I haven't been using PHP for many years, couldn't get what the problem is. Please file a PR if you found a working fix.

**Comment by LufoX11** [comment]
Done: https://github.com/myst729/wp-reposidget/pull/6

Please update it in Wordpress (I don't know how plugin repos work there) so changes can be automatically be updated in the plugin.

Thank you!

**Comment by myst729** [comment]
> Done: #6
> 
> Please update it in Wordpress (I don't know how plugin repos work there) so changes can be automatically be updated in the plugin.
> 
> Thank you!

Updated. Thanks for your contribution.
